_core:
  default_config_hash: dO7ksVrRzn4zZIbRkzcsdk-J7S6XyCVtEXXEw4JybMg
button_link_styles:
  usa-button: Primary
  usa-button--secondary: Secondary
  usa-button--text: Text
override_type: 1
override_size: 1
override_status: 0
override_target: 1
