# Design Tokens
# Define basic design variables here.
uswds:
  # https://github.com/uswds/uswds/blob/develop/src/stylesheets/theme/_uswds-theme-general.scss
  image-path: '../dist/images'
  show-compile-warnings: false
  show-notifications: false
  # https://github.com/uswds/uswds/blob/develop/src/stylesheets/theme/_uswds-theme-typography.scss
  font-path: 'fonts'
  font-type-mono: false
  font-type-sans: 'public-sans'
  font-type-serif: false
  font-role-ui: "sans"
  font-role-heading: "sans"
  font-role-body: "sans"
  font-role-code: "sans"
  font-role-alt: "sans"
  type-scale-md: 7
  lead-font-family: "sans"
  
  # https://designsystem.digital.gov/design-tokens/typesetting/font-size/#system-tokens
  h1-font-size: 11 # 28px (comp was 26px)
  h2-font-size: 10 # 24px (comp was 23px)
  h3-font-size: 7 # 18px
  h4-font-size: 5 # 16px
  h5-font-size: 3 # 14px
  h6-font-size: 1 # 12px
  small-font-size: 2 # 13px
  body-font-size: 4 # 15px
  display-font-size: 4 # 15px
  lead-font-size: 6 # 17px

  # https://designsystem.digital.gov/design-tokens/typesetting/line-height/
  body-line-height: 5 # 1.62
  heading-line-height: 2 # 1.15 (comp was 1.2 on most)
  lead-line-height: 5 # 1.62

  # https://github.com/uswds/uswds/blob/develop/src/stylesheets/theme/_uswds-theme-spacing.scss
  column-gap-desktop: 5
  grid-container-max-width: 'desktop'
  site-margins-width: 4
  site-margins-mobile-width: 2

  # https://github.com/uswds/uswds/blob/develop/src/stylesheets/theme/_uswds-theme-color.scss
  # Moved custom color definitions into _uswds-theme-colors.scss
  body-background-color: 'white'
  text-color: 'base-darkest'
  text-reverse-color: 'white'
  link-color: 'primary-dark'
  # link-visited-color: 'violet-70v'
  link-hover-color: 'primary-vivid'
  link-active-color: 'primary-vivid'
gesso:
  palette:
    uswds:
      primary:
        lightest: !sass
          sass: 'color(primary-lightest)'
          fallback: '#f3f7fe'
        lighter: !sass
          sass: 'color(primary-lighter)'
          fallback: '#e7f0fe'
        light: !sass
          sass: 'color(primary-light)'
          fallback: '#c4dafc'
        base: !sass
          sass: 'color(primary)'
          fallback: '#3168b7'
        vivid: !sass
          sass: 'color(primary-vivid)'
          fallback: '#0064f0'
        dark: !sass
          sass: 'color(primary-dark)'
          fallback: '#01409b'
        darker: !sass
          sass: 'color(primary-darker)'
          fallback: '#003179'
      secondary:
        lightest: !sass
          sass: 'color(secondary-lighter)'
          fallback: '#f3f5d9'
        lighter: !sass
          sass: 'color(secondary-lighter)'
          fallback: '#e6eab4'
        light: !sass
          sass: 'color(secondary-light)'
          fallback: '#d7de86'
        base: !sass
          sass: 'color(secondary)'
          fallback: '#bdce31'
      base:
        lightest: !sass
          sass: 'color(base-lightest)'
          fallback: '#f3f3f3'
        lighter: !sass
          sass: 'color(base-lighter)'
          fallback: '#d1d1d1'
        light: !sass
          sass: 'color(base-light)'
          fallback: '#aeaeae'
        base: !sass
          sass: 'color(base)'
          fallback: '#8b8b8b'
        dark: !sass
          sass: 'color(base-dark)'
          fallback: '#686868'
        darker: !sass
          sass: 'color(base-darker)'
          fallback: '#454545'
        darkest: !sass
          sass: 'color(base-darkest)'
          fallback: '#171717'
        white: !sass
          sass: 'color("white")'
          fallback: '#fff'
        black: !sass
          sass: 'color("black")'
          fallback: '#000'
  box-shadow:
    0: !sass
      sass: 'get-uswds-value(box-shadow, none)'
      fallback: 'none'
    1: !sass
      sass: 'get-uswds-value(box-shadow, 1)'
      fallback: '0 1px 4px 0 rgba(0, 0, 0, 0.1)'
    2: !sass
      sass: 'get-uswds-value(box-shadow, 2)'
      fallback: '0 4px 8px 0 rgba(0, 0, 0, 0.1)'
    3: !sass
      sass: 'get-uswds-value(box-shadow, 3)'
      fallback: '0 8px 16px 0 rgba(0, 0, 0, 0.1)'
    4: !sass
      sass: 'get-uswds-value(box-shadow, 4)'
      fallback: '0 12px 24px 0 rgba(0, 0, 0, 0.1)'
    5: !sass
      sass: 'get-uswds-value(box-shadow, 5)'
      fallback: '0 16px 32px 0 rgba(0, 0, 0, 0.1)'
  constrains:
    sm: 800px
    md: !uswds uswds.grid-container-max-width
    lg: 2200px
  breakpoints:
    mobile: !sass
      sass: 'units(mobile)'
      fallback: 320px
    mobile-lg: !sass
      sass: 'units(mobile-lg)'
      fallback: 480px
    tablet: !sass
      sass: 'units(tablet)'
      fallback: 640px
    tablet-lg: !sass
      sass: 'units(tablet-lg)'
      fallback: 880px
    desktop: !sass
      sass: 'units(desktop)'
      fallback: 1024px
    desktop-lg: !sass
      sass: 'units(desktop-lg)'
      fallback: 1200px
    widescreen: !sass
      sass: 'units(widescreen)'
      fallback: 1400px
  colors:
    text:
      primary: !sass
        sass: 'color($theme-text-color)'
        fallback: '#171717'
      link: !sass
        sass: 'color($theme-link-color)'
        fallback: '#3168b7'
      link-hover: !sass
        sass: 'color($theme-link-hover-color)'
        fallback: '#0064f0'
    background:
      site: !sass
        sass: 'color($theme-body-background-color)'
        fallback: '#fff'
    button:
      primary:
        background: uswds.primary.base
        background-hover: uswds.primary.dark
        background-active: uswds.primary.dark
        border: uswds.primary.base
        border-hover: uswds.primary.dark
        text: uswds.base.white
        text-hover: uswds.base.white
        text-active: uswds.base.white
      secondary:
        background: uswds.base.white
        background-hover: uswds.primary.dark
        background-active: uswds.primary.dark
        border: uswds.primary.base
        border-hover: uswds.primary.dark
        text: uswds.primary.dark
        text-hover: uswds.base.white
        text-active: uswds.base.white
      disabled:
        background: uswds.base.light
        border: uswds.base.light
        text: uswds.base.white
      back-to-top:
        background: uswds.base.white
        background-hover: uswds.primary.dark
        background-active: uswds.primary.dark
        border: uswds.primary.base
        border-hover: uswds.primary.dark
        text: uswds.primary.dark
        text-hover: uswds.base.white
        text-active: uswds.base.white
    form:
      background: uswds.base.white
      background-active: uswds.base.white
      background-checked: uswds.primary.base
      background-unchecked: uswds.base.white
      border: uswds.base.lighter
      border-dark: uswds.base.lighter
      border-light: uswds.base.lighter
      thumb: uswds.base.lighter
      track: uswds.base.lighter
    selection:
      background: uswds.primary.base
    ui:
      generic:
        border: !sass
          sass: '$theme-color-base-lighter-transparent'
      text: uswds.base.white
  typography:
    font-family:
      body:
        name: Body
        stack: !sass
          sass: 'font-family(body)'
        demo: true
      heading:
        name: Heading
        stack: !sass
          sass: 'font-family(heading)'
        demo: true
      code:
        name: Code
        stack: !sass
          sass: 'font-family(mono)'
        demo: false
      ui:
        name: UI
        stack: !sass
          sass: 'font-family(ui)'
        demo: false
      alt:
        name: Alternate
        stack: !sass
          sass: 'font-family(alt)'
        demo: false
    base-font-size: 16px # Changing this value will throw off USWDS calculations.
    font-weight:
      light: !sass
        sass: 'font-weight(light)'
        fallback: 300
      normal: !sass
        sass: 'font-weight(normal)'
        fallback: 400
      bold: !sass
        sass: 'font-weight(bold)'
        fallback: 700
    line-height:
      1: 1
      2: 1.2
      3: 1.35
      4: 1.5
      5: 1.62
      6: 1.75
    display:
      h1:
        font-family: heading.stack
        font-size: !sass
          sass: 'font-size(heading, $theme-h1-font-size)'
        font-weight: bold
        line-height: !sass
          sass: 'line-height(heading, $theme-heading-line-height)'
      h2:
        font-family: heading.stack
        font-size: !sass
          sass: 'font-size(heading, $theme-h2-font-size)'
        font-weight: bold
        line-height: !sass
          sass: 'line-height(heading, $theme-heading-line-height)'
      h3:
        font-family: heading.stack
        font-size: !sass
          sass: 'font-size(heading, $theme-h3-font-size)'
        font-weight: bold
        line-height: !sass
          sass: 'line-height(heading, $theme-heading-line-height)'
      h4:
        font-family: heading.stack
        font-size: !sass
          sass: 'font-size(heading, $theme-h4-font-size)'
        font-weight: bold
        line-height: !sass
          sass: 'line-height(heading, $theme-heading-line-height)'
      h5:
        font-family: heading.stack
        font-size: !sass
          sass: 'font-size(heading, $theme-h5-font-size)'
        font-weight: bold
        line-height: !sass
          sass: 'line-height(heading, $theme-heading-line-height)'
      h6:
        font-family: body.stack
        font-size: !sass
          sass: 'font-size(body, $theme-h6-font-size)'
        font-weight: normal
        letter-spacing: !sass
          sass: 'ls(1)'
        line-height: !sass
          sass: 'line-height(body, $theme-heading-line-height)'
        text-transform: uppercase
      blockquote:
        font-family: alt.stack
        font-size: !sass
          sass: 'font-size(body, $theme-body-font-size)'
        font-weight: normal
        line-height: !sass
          sass: 'line-height(alt, $theme-body-line-height)'
      body:
        font-family: body.stack
        font-size: !sass
          sass: 'font-size(body, $theme-body-font-size)'
        font-weight: normal
        line-height: !sass
          sass: 'line-height(body, $theme-body-line-height)'
      lead:
        font-family: !sass
          sass: 'family($theme-lead-font-family)'
        font-size: !sass
          sass: 'font-size($theme-lead-font-family, $theme-lead-font-size)'
        font-weight: light
        line-height: !sass
          sass: 'line-height($theme-lead-font-family, $theme-lead-line-height)'
  transitions:
    ease:
      ease-in-out: 'cubic-bezier(0.4, 0, 0.2, 1)'
      ease-out: 'cubic-bezier(0.0, 0, 0.2, 1)'
      ease-in: 'cubic-bezier(0.4, 0, 1, 1)'
      sharp: 'cubic-bezier(0.4, 0, 0.6, 1)'
    duration:
      shortest: 150ms
      short: 200ms
      standard: 375ms
      long: 400ms
      intro: 270ms
      outro: 195ms
  z-index:
    nav: 1000
    drawer: 1200
    modal: 1300
  spacing:
    '05': !sass
      sass: "units('05')"
      fallback: '4px'
    1: !sass
      sass: 'units(1)'
      fallback: '8px'
    1.5: !sass
      sass: "units(1.5)"
      fallback: '12px'
    2: !sass
      sass: 'units(2)'
      fallback: '16px'
    2.5: !sass
      sass: "units(2.5)"
      fallback: '20px'
    3: !sass
      sass: 'units(3)'
      fallback: '24px'
    4: !sass
      sass: 'units(4)'
      fallback: '32px'
    5: !sass
      sass: 'units(5)'
      fallback: '40px'
    6: !sass
      sass: 'units(6)'
      fallback: '48px'
    7: !sass
      sass: 'units(7)'
      fallback: '56px'
    8: !sass
      sass: 'units(8)'
      fallback: '64px'
    9: !sass
      sass: 'units(9)'
      fallback: '72px'
    10: !sass
      sass: 'units(10)'
      fallback: '80px'
    15: !sass
      sass: 'units(15)'
      fallback: '120px'
  gutter-width: !uswds uswds.column-gap-desktop
  site-margins:
    'mobile': !uswds uswds.site-margins-mobile-width
    'desktop': !uswds uswds.site-margins-width
