_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  admin_toolbar: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor5: 0
  comment: 0
  components: 0
  config: 0
  contact: 0
  contextual: 0
  datetime: 0
  dblog: 0
  devel: 0
  dynamic_page_cache: 0
  editor: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  gesso_helper: 0
  help: 0
  history: 0
  image: 0
  link: 0
  menu_link_content: 0
  menu_ui: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  search: 0
  shortcut: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  twig_tweak: 0
  update: 0
  user: 0
  views_ui: 0
  webform: 0
  webform_access: 0
  webform_demo_application_evaluation: 0
  webform_demo_event_registration: 0
  webform_demo_region_contact: 0
  webform_devel: 0
  webform_example_composite: 0
  webform_example_custom_form: 0
  webform_example_element: 0
  webform_example_element_properties: 0
  webform_example_handler: 0
  webform_example_remote_post: 0
  webform_example_variant: 0
  webform_examples: 0
  webform_examples_accessibility: 0
  webform_node: 0
  webform_options_limit: 0
  webform_scheduled_email: 0
  webform_share: 0
  webform_ui: 0
  views: 10
  standard: 1000
theme:
  olivero: 0
  claro: 0
  aphis: 0
profile: standard
